apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion
  labels:
    app: currency-conversion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - name: currency-conversion
        image: krstic8687/mmv1-currency-conversion-service:0.0.12-SNAPSHOT
        envFrom:
          - configMapRef:
              name: currency-conversion
#       env:
#         - name: CURRENCY_EXCHANGE_URI
#           value: http://currency-exchange
        ports:
        - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: currency-conversion
spec:
  selector:
    app: currency-conversion
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
---
apiVersion: v1
data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange
kind: ConfigMap
metadata:
  name: currency-conversion
  namespace: default
