apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange
  labels:
    app: currency-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-exchange
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
      - name: currency-exchange
        image: krstic8687/mmv1-currency-exchange-service:0.0.12-SNAPSHOT
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8000
          initialDelaySeconds: 180
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8000
          initialDelaySeconds: 180
          periodSeconds: 15
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer
